### PR TITLE
Add integration tests to the Apache Tomcat Migration Tool for Jakarta EE

### PR DESCRIPTION
**Pull request by alitokmen**
* Updated structure, with parent and children
* Added a new WAR which tests @WebServlet annotations, Datasources, JMS queues and topics, a mail session as well as a "non transformation" check servlet which parses an XML file (and hence behind the scenes the non-Jakarta-EE javax.xml packages are left as is)
  => The same WAR artifact creation also executes the Apache Tomcat Migration Tool for Jakarta EE to create the Jakarta EE version
* Added a new EAR, with EJBs accessed from a WAR
  => The same EAR artifact creation also executes the Apache Tomcat Migration Tool for Jakarta EE to create the Jakarta EE version, due to current limitations it executes separately on the EJB JAR and on the WAR before reassembling the EAR
* Added integration tests of the Java EE and Jakarta EE WARs on a Java EE container
  => This checks that the Java EE versions work, and that the Jakarta EE versions don't
* Added integration tests of the Java EE and Jakarta EE WARs on a Jakarta EE container
  => This checks that the Java EE versions don't work, and that the Jakarta EE versions do

### CODE REVIEW

**Comment by alitokmen** [comment]
Is there a reason why Travis is configured to skip tests?

**Comment by alitokmen** [comment]
Also, the number Coverall is reporting is wrong: the servlets obviously don't have unit tests, they have integration tests which Coverall cannot link to the servlet code 🥺

**Comment by martin-g** [comment]
> Can someone update that please?

You can do this yourself by adding `script: mvn verify` step to .travis.yml

**Review by martin-g — APPROVED** [review]

**Comment by alitokmen** [comment]
I closed the fork as all is ready - Is there a process to follow to get the PR merged?

**Comment by alitokmen** [comment]
@martin-g , after approval are there any steps to follow to get the PR merged?

**Comment by rmaucher** [comment]
I just don't see the point of this, except I often see tests for super obvious stuff elsewhere so I guess this has value to some people. The only problem is that elsewhere the same reasoning does not cause adding of a big blob of stuff just for that purpose. I think you can test out the same thing by checking the results casually instead of using a slow and clunky real live app test. This kind of integration testing could also go in the Tomcat testsuite instead, there it would be rather invisible.

**Comment by alitokmen** [comment]
@rmaucher , thanks for your feedback.

What I observed during the voting of new versions of the Jakarta EE migrator is that there are people manually executing the migrator on existing Java Web projects and then deploy them on an existing Tomcat version.

This PR does the exact same, automatically. It can be used as a starting point, where one can easily also add the Tomcat example / sample WARs - Assuming these are in Maven repositories. It uses TomEE for these tests (instead of pure Tomcat) as some tests use JMS and EJBs, which are not part of the "pure Tomcat" scope.

I see your point about build time, if you want I can tweak the profiles and the Travis YAML so these are only executed by Travis; and developers do their work "as fast as possible".

**Comment by rmaucher** [comment]
The release of the tool will be tied to Tomcat testing since this is a subcomponent. This integration testing can be either in the Tomcat testsuite in a limited form [and we actually need to check that the integrated auto migration works, so it has to be done] or in a separate repository of your own if you want to add whatever you want [this seems to be the case].

**Pull request closed without merging**
